CarRental/Controllers/CarsController.cs
using CarRental.Data;
using CarRental.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using System.Linq;
using System.Threading.Tasks;

namespace CarRental.Controllers
{
    public class CarsController : Controller
    {
        private readonly DefaultContext _context;
        private readonly IConfiguration _configuration;

        public CarsController(DefaultContext context, IConfiguration configuration)
        {
            _context = context;
            _configuration = configuration;
        }

        // GET: Cars
        public async Task<IActionResult> Index()
        {
            return View(await _context.Cars.ToListAsync());
        }

        // GET: Cars/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = await _context.Cars
                .FirstOrDefaultAsync(m => m.Id == id);
            if (car == null)
            {
                return NotFound();
            }

            return View(car);
        }

        // GET: Cars/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Cars/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Car car)
        {
            if (ModelState.IsValid)
            {
                using (var connection = new SqlConnection(_configuration.GetConnectionString("DefaultContext")))
                {
                    await connection.OpenAsync();
                    using (var command = new SqlCommand("[dbo].[car_registration]", connection))
                    {
                        command.CommandType = System.Data.CommandType.StoredProcedure;
                        command.Parameters.AddWithValue("@brand", car.Brand);
                        command.Parameters.AddWithValue("@model", car.Model);
                        command.Parameters.AddWithValue("@number", car.StateNumber);
                        command.Parameters.AddWithValue("@is_truck", car.IsTruck);
                        command.Parameters.AddWithValue("@price_per_day", car.RentalPricePerDay);
                        _ = await command.ExecuteNonQueryAsync();
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(car);
        }

        // GET: Cars/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = await _context.Cars.FindAsync(id);
            if (car == null)
            {
                return NotFound();
            }
            return View(car);
        }

        // POST: Cars/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, Car car)
        {
            if (id != car.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(car);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CarExists(car.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(car);
        }

        // GET: Cars/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = await _context.Cars
                .FirstOrDefaultAsync(m => m.Id == id);
            if (car == null)
            {
                return NotFound();
            }

            return View(car);
        }

        // POST: Cars/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var car = await _context.Cars.FindAsync(id);
            _context.Cars.Remove(car);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CarExists(long id)
        {
            return _context.Cars.Any(e => e.Id == id);
        }
    }
}

CarRental/Controllers/ClientsController.cs
using CarRental.Data;
using CarRental.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using System.Linq;
using System.Threading.Tasks;

namespace CarRental.Controllers
{
    public class ClientsController : Controller
    {
        private readonly DefaultContext _context;
        private readonly IConfiguration _configuration;

        public ClientsController(DefaultContext context, IConfiguration configuration)
        {
            _context = context;
            _configuration = configuration;
        }

        // GET: Clients
        public async Task<IActionResult> Index()
        {
            return View(await _context.Clients.ToListAsync());
        }

        // GET: Clients/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var client = await _context.Clients
                .FirstOrDefaultAsync(m => m.Id == id);
            if (client == null)
            {
                return NotFound();
            }

            return View(client);
        }

        // GET: Clients/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Clients/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Client client)
        {
            if (ModelState.IsValid)
            {
                using (var connection = new SqlConnection(_configuration.GetConnectionString("DefaultContext")))
                {
                    await connection.OpenAsync();
                    using (var command = new SqlCommand("[dbo].[client_registration]", connection))
                    {
                        command.CommandType = System.Data.CommandType.StoredProcedure;
                        command.Parameters.AddWithValue("@first_name", client.FirstName);
                        command.Parameters.AddWithValue("@second_name", client.SecondName);
                        command.Parameters.AddWithValue("@last_name", client.LastName);
                        command.Parameters.AddWithValue("@passport", client.Passport);
                        command.Parameters.AddWithValue("@date_of_birth", client.DateOfBirth);
                        command.Parameters.AddWithValue("@phone", new string(client.Phone.Where(c => char.IsDigit(c)).ToArray()));
                        _ = await command.ExecuteNonQueryAsync();
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(client);
        }

        // GET: Clients/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var client = await _context.Clients.FindAsync(id);
            if (client == null)
            {
                return NotFound();
            }
            return View(client);
        }

        // POST: Clients/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, Client client)
        {
            if (id != client.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    client.Phone = new string(client.Phone.Where(c => char.IsDigit(c)).ToArray());
                    _context.Update(client);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClientExists(client.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(client);
        }

        // GET: Clients/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var client = await _context.Clients
                .FirstOrDefaultAsync(m => m.Id == id);
            if (client == null)
            {
                return NotFound();
            }

            return View(client);
        }

        // POST: Clients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var client = await _context.Clients.FindAsync(id);
            _context.Clients.Remove(client);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClientExists(long id)
        {
            return _context.Clients.Any(e => e.Id == id);
        }
    }
}

CarRental/Controllers/RentalsController.cs
using CarRental.Data;
using CarRental.Extensions;
using CarRental.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace CarRental.Controllers
{
    public class RentalsController : Controller
    {
        private readonly DefaultContext _context;
        private readonly IConfiguration _configuration;

        public RentalsController(DefaultContext context, IConfiguration configuration)
        {
            _context = context;
            _configuration = configuration;
        }

        public async Task<IActionResult> Index(RentalFiltersModel filters)
        { 
            var defaultContext = _context.Rentals.Include(r => r.Car).Include(r => r.Client).Select(r => r);
            if (filters.From.HasValue)
                defaultContext = defaultContext.Where(r => r.StartDateTime >= filters.From);

            if (filters.To.HasValue)
                defaultContext = defaultContext.Where(r => r.EndDateTime <= filters.To);

            if (filters.SortOrder == Models.SortOrder.Asc)
                switch (filters.SortBy)
                {
                    case RentalSort.EndDateTime:
                        defaultContext = defaultContext.OrderBy(r => r.EndDateTime);
                        break;
                    case RentalSort.StartDateTime:
                        defaultContext = defaultContext.OrderBy(r => r.StartDateTime);
                        break;
                }
            else
                switch (filters.SortBy)
                {
                    case RentalSort.EndDateTime:
                        defaultContext = defaultContext.OrderByDescending(r => r.EndDateTime);
                        break;
                    case RentalSort.StartDateTime:
                        defaultContext = defaultContext.OrderByDescending(r => r.StartDateTime);
                        break;
                }
            var model = new RentalListModel
            {
                Filters = filters,
                Rentals = defaultContext.ToList()
            };
            ViewBag.SortBy = Enum.GetValues<RentalSort>().Select(r => new SelectListItem(r.GetDescription(), $"{(int)r}"));
            return View(model);
        }

        // GET: Rentals/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rental = await _context.Rentals
                .Include(r => r.Car)
                .Include(r => r.Client)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (rental == null)
            {
                return NotFound();
            }

            return View(rental);
        }

        // GET: Rentals/Create
        public IActionResult Create()
        {
            ViewData["CarId"] = new SelectList(_context.Cars, "Id", "DisplayName");
            ViewData["ClientId"] = new SelectList(_context.Clients, "Id", "FullName");
            return View();
        }

        // POST: Rentals/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Rental rental)
        {
            if (ModelState.IsValid)
            {
                using (var connection = new SqlConnection(_configuration.GetConnectionString("DefaultContext")))
                {
                    await connection.OpenAsync();
                    using (var command = new SqlCommand("[dbo].[rental_registration]", connection))
                    {
                        command.CommandType = System.Data.CommandType.StoredProcedure;
                        command.Parameters.AddWithValue("@client_id", rental.ClientId);
                        command.Parameters.AddWithValue("@car_id", rental.CarId);
                        command.Parameters.AddWithValue("@contract_number", rental.ContractNumber);
                        command.Parameters.AddWithValue("@start_datetime", rental.StartDateTime);
                        command.Parameters.AddWithValue("@number_of_days", rental.NumberOfDays);
                        _ = await command.ExecuteNonQueryAsync();
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CarId"] = new SelectList(_context.Cars, "Id", "DisplayName", rental.CarId);
            ViewData["ClientId"] = new SelectList(_context.Clients, "Id", "FullName", rental.ClientId);
            return View(rental);
        }

        // GET: Rentals/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rental = await _context.Rentals.FindAsync(id);
            if (rental == null)
            {
                return NotFound();
            }
            ViewData["CarId"] = new SelectList(_context.Cars, "Id", "DisplayName", rental.CarId);
            ViewData["ClientId"] = new SelectList(_context.Clients, "Id", "FullName", rental.ClientId);
            return View(rental);
        }

        // POST: Rentals/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, Rental rental)
        {
            if (id != rental.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(rental);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RentalExists(rental.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CarId"] = new SelectList(_context.Cars, "Id", "DisplayName", rental.CarId);
            ViewData["ClientId"] = new SelectList(_context.Clients, "Id", "FullName", rental.ClientId);
            return View(rental);
        }

        // GET: Rentals/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rental = await _context.Rentals
                .Include(r => r.Car)
                .Include(r => r.Client)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (rental == null)
            {
                return NotFound();
            }

            return View(rental);
        }

        // POST: Rentals/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var rental = await _context.Rentals.FindAsync(id);
            _context.Rentals.Remove(rental);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RentalExists(long id)
        {
            return _context.Rentals.Any(e => e.Id == id);
        }
    }
}

CarRental/Views/Rentals/Create.cshtml
@model CarRental.Models.Rental

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Rental</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ClientId" class="control-label"></label>
                <select asp-for="ClientId" class ="form-control" asp-items="ViewBag.ClientId"></select>
            </div>
            <div class="form-group">
                <label asp-for="CarId" class="control-label"></label>
                <select asp-for="CarId" class ="form-control" asp-items="ViewBag.CarId"></select>
            </div>
            <div class="form-group">
                <label asp-for="ContractNumber" class="control-label"></label>
                <input asp-for="ContractNumber" class="form-control" />
                <span asp-validation-for="ContractNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDateTime" class="control-label"></label>
                <input asp-for="StartDateTime" class="form-control" />
                <span asp-validation-for="StartDateTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberOfDays" class="control-label"></label>
                <input asp-for="NumberOfDays" class="form-control" />
                <span asp-validation-for="NumberOfDays" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CarRental/Views/Rentals/Delete.cshtml
@model CarRental.Models.Rental

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Rental</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Client)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Client.FirstName)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Car)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Car.Brand)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ContractNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ContractNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FullPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FullPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDateTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDateTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndDateTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndDateTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumberOfDays)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumberOfDays)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CarRental/Views/Rentals/Details.cshtml
@model CarRental.Models.Rental

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Rental</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Client)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Client.FullName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Car)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Car.DisplayName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ContractNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ContractNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FullPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FullPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDateTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDateTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndDateTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndDateTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumberOfDays)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumberOfDays)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

CarRental/Views/Rentals/Edit.cshtml
@model CarRental.Models.Rental

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Rental</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ClientId" class="control-label"></label>
                <select asp-for="ClientId" class="form-control" asp-items="ViewBag.ClientId"></select>
                <span asp-validation-for="ClientId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CarId" class="control-label"></label>
                <select asp-for="CarId" class="form-control" asp-items="ViewBag.CarId"></select>
                <span asp-validation-for="CarId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContractNumber" class="control-label"></label>
                <input asp-for="ContractNumber" class="form-control" />
                <span asp-validation-for="ContractNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FullPrice" class="control-label"></label>
                <input asp-for="FullPrice" class="form-control" />
                <span asp-validation-for="FullPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDateTime" class="control-label"></label>
                <input asp-for="StartDateTime" class="form-control" />
                <span asp-validation-for="StartDateTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberOfDays" class="control-label"></label>
                <input asp-for="NumberOfDays" class="form-control" />
                <span asp-validation-for="NumberOfDays" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CarRental/Views/Rentals/Index.cshtml
@model RentalListModel

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
@await Html.PartialAsync("_Filters", Model.Filters)
<table class="table">
    <thead>
        <tr>
            <th>
                Client
            </th>
            <th>
                Car
            </th>
            <th>
                Contract number
            </th>
            <th>
                Full price
            </th>
            <th>
                Start date and time
            </th>
            <th>
                End date and time
            </th>
            <th>
                Number of days
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Rentals) {
        <tr>
            <td>
                <a asp-action="Details" asp-controller="Clients" asp-route-id="@item.Client.Id">@Html.DisplayFor(modelItem => item.Client.FullName)</a>
            </td>
            <td>
                <a asp-action="Details" asp-controller="Cars" asp-route-id="@item.Car.Id">@Html.DisplayFor(modelItem => item.Car.DisplayName)</a>
</td>
            <td>
                @Html.DisplayFor(modelItem => item.ContractNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FullPrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StartDateTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EndDateTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumberOfDays)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

CarRental/Views/Rentals/_Filters.cshtml
@model RentalFiltersModel 

<form class="row" asp-action="Index" asp-controller="Rentals" method="post">
    <div class="form-group col">
        <label asp-for="SortBy" class="control-label"></label>
        <select asp-for="SortBy" class="form-control" asp-items="@ViewBag.SortBy"></select>
    </div>
    <div class="form-group col">
        <label asp-for="SortOrder" class="control-label"></label>
        <select asp-for="SortOrder" class="form-control" asp-items="@Html.GetEnumSelectList<SortOrder>()"></select>
    </div>
    <div class="form-group col">
        <label asp-for="From" class="control-label"></label>
        <input asp-for="From" class="form-control" />
    </div>
    <div class="form-group col">
        <label asp-for="To" class="control-label"></label>
        <input asp-for="To" class="form-control" />
    </div>
    <div class="form-group col-2 align-self-end">
        <button type="submit" class="btn btn-outline-dark">Apply</button>
    </div>
</form>